name: flexi_flow
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_analytics: ^11.4.5  # Updated version
  firebase_data_connect: ^0.1.4
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  lottie: ^3.3.0
  fl_chart: ^0.71.0
  url_launcher: ^6.3.1
  flutter_local_notifications: ^15.1.1
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  animate_do: ^3.0.2
  confetti: ^0.7.0
  audioplayers: ^5.1.0
  intl: ^0.19.0
  http: ^1.3.0
  timezone: ^0.9.2  # For timezone support
  universal_html: ^2.2.4
  lucide_icons: ^0.257.0
  font_awesome_flutter: ^10.4.0
  iconsax: ^0.0.8

  shimmer: ^3.0.0
  glassmorphism: ^2.0.0
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/newflex.png
    - assets/images/flexlogo.png
    - assets/animations/animation.json
    - assets/animations/log_animation.json
    - assets/animations/recomm.json
    - assets/animations/friendly_support.json
    - exercise.png
    - assets/animations/firststep.json
    - assets/animations/1week.json
    - assets/animations/hero.json
    - assets/animations/monthly.json
    - assets/animations/yeah-96783.mp3
    - assets/animations/keepgoing.json
    - assets/animations/acheivements.json
    - assets/animations/community.json
    - assets/animations/exercise.json
    - assets/animations/logdietmeds.json
    - assets/animations/logpain.json
    - assets/animations/progress.json
    - assets/animations/about.json
    - assets/animations/contact.json

